version: "3.3"

services:
  reverseproxy:
    build:
      context: ./ops/nginx
      dockerfile: Dockerfile
    ports:
          - 8080:8080
          - 8081:8081
    restart: always

  nginx:
      depends_on:
          - reverseproxy
      image: nginx:alpine
      restart: always

  apache:
      depends_on:
          - reverseproxy
      image: httpd:alpine
      restart: always
  # backend:
  #   build:
  #     context: ./packages/backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./packages/backend:/app/backend
  #   depends_on: 
  #     - reverseproxy
  #   ports:
  #     - 4000:4000
    
  # frontend:
  #   build:
  #     context: ./packages/frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./packages/frontend:/app/frontend
  #   depends_on: 
  #     - backend
  #     - reverseproxy
  #   ports:
  #     - 3000:3000
    
volumes:
  # frontend: {}
  # backend: {}
  reverseproxy: {}